apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
  namespace: app-noticias
spec:
  # quando nao declara o numero de replicas, o padrao e 1
  template:
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: db-noticias
